version: "3.3"

services:

  db:
    image: mysql:8.0.25
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD:  "${MYSQL_USER_PASS}"
      MYSQL_ROOT_PASSWORD:  "${MYSQL_USER_PASS}"
      MYSQL_DATABASE:  "${MY_SQL_DATABASE}"

    volumes:
      - mysql_db:/usr/lib/mysql
    networks:
      uuc:
        ipv4_address: '172.20.1.4'
    
    

  dns:
    image: store/internetsystemsconsortium/bind9:9.11
    container_name: dns
    volumes:
      -  dns:/var/lib/bind/
      - ./backend/dns/forward.uurnikconnect.com:/var/lib/bind/forward.uurnikconnect.com
      - ./backend/dns/named.conf:/etc/bind/named.conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    network_mode: host
    


  api:
    build: ./backend/
    env_file: .env
    image: uuc_api
    container_name: uuc_api
    image: uuc_api
    volumes:
      - "./backend/:/code"
    ports:
      - 8001:80
    command: ['bash', '/code/scripts/run_dev.sh']
    depends_on:
      - db
    networks:
      uuc:
        ipv4_address: '172.20.1.5'



  dnsupdater:
    build:
      context: ./backend/dnsupdater
      dockerfile: Dockerfile-dnsupdater
    container_name: dnsupdater
    image: dnsupdater
    extra_hosts:
      - "dockerhost:172.20.1.1"
    ports:
      - "8080:8080"
    networks:
      uuc:
        ipv4_address: '172.20.1.6'
  

  frontend:
    build:
      context: ./frontend
    container_name: vue-app
    # env_file: .env
    environment: 
      - VUE_APP_BACKEND=${VUE_APP_BACKEND}
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "8081:3000"
    networks:
      uuc:
        ipv4_address: '172.20.1.8'


   

volumes:
  dns:
  mysql_db:
  
networks:
  uuc:
    ipam:
      driver: default
      config:
        - subnet: '172.20.1.0/24'