from django.urls import path
from api.views import (
    summary,
    add_Host,
    get_inventory,
    configure,
    add_remove_spoke,
    get_facts,
    reachability,
    tear_down,
    get_cdp_info,
    add_remove_hub,
    delete_host,
    check_alive,
    ip_sla_conf,
    gather_routes,
    get_deployed_access_type,
    get_interfaces,
    copp,
    device_hardening,
    snmp_poll,
    swipe_ipsec_keys,
    set_logging,
    ping_test
)

urlpatterns = [
    path("hosts", add_Host),
    path("hosts/delete/<str:pk>/", delete_host),
    path("inventory/", get_inventory),
    path("configure/<int:option>/", configure),
    path("branch/<str:pk>/", add_remove_spoke),
    path("facts/", get_facts),
    path("ping/", reachability),
    path("alive/", check_alive),
    path("tear-down/", tear_down),
    path("neighbors/", get_cdp_info),
    path("hub/<str:pk>/", add_remove_hub),
    path("ip-sla/", ip_sla_conf),
    path("routing/", gather_routes),
    path("access-type/", get_deployed_access_type),
    path("interfaces/<str:name>/", get_interfaces),
    path("copp/", copp),
    path("device-hardening/", device_hardening),
    path("snmp/", snmp_poll),
    path("change-keys-ipsec/", swipe_ipsec_keys),
    path("logging/<str:pk>/", set_logging),
    path("summary", summary),
    path("testconn", ping_test),


]
