FROM python:3.8-alpine
WORKDIR /code
COPY ./requirements-dnsupdater.txt /code/
RUN python -m pip install --upgrade pip
RUN pip install -r requirements-dnsupdater.txt
COPY ./main.py /code/
EXPOSE 8080
CMD gunicorn --bind 0.0.0.0:8080 main:app