# Generated by Django 3.1 on 2020-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CacheTable",
            fields=[
                (
                    "ip",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("in_use", models.BooleanField(default=False)),
                ("device_ip", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Defaults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tunnel_int", models.CharField(default="414", max_length=5)),
                ("asn", models.CharField(default="65414", max_length=5)),
                ("policy_num", models.CharField(default="22", max_length=5)),
                ("ipsec_key", models.CharField(default="uurnik123", max_length=16)),
                ("trans_name", models.CharField(default="UURNIK", max_length=15)),
                (
                    "profile_name",
                    models.CharField(default="UURNIK_CONNECT", max_length=15),
                ),
                ("nhs_server", models.CharField(default="none", max_length=15)),
                ("nhs_nbma", models.CharField(default="none", max_length=15)),
                ("access_type", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hosts",
            fields=[
                ("ip", models.CharField(max_length=15, serialize=False)),
                ("name", models.CharField(max_length=30, primary_key=True)),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(default=False, max_length=30)),
                ("platform", models.CharField(default="ios", max_length=20)),
                ("group", models.CharField(default=False, max_length=6)),
                ("is_configured", models.BooleanField(default=False)),
                ("wan_int", models.CharField(blank=True, max_length=30)),
                ("wan_subnet", models.CharField(blank=True, max_length=15)),
                ("next_hop", models.CharField(blank=True, max_length=15)),
                ("tunnel_ip", models.CharField(blank=True, max_length=30)),
                ("loop_back", models.CharField(blank=True, max_length=35)),
                ("vendor", models.CharField(blank=True, max_length=40)),
                ("model", models.CharField(blank=True, max_length=30)),
                ("os_version", models.TextField(blank=True, max_length=100)),
                ("serial_no", models.CharField(blank=True, max_length=50)),
                ("dev_name", models.TextField(blank=True, max_length=30)),
                ("interfaces", models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TunnelPool",
            fields=[
                (
                    "ip",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
    ]
