# Generated by Django 3.1 on 2020-08-20 06:36

from django.db import transaction
from django.db import migrations
from api.helpers.get_tunnel_pool_list import add_tunnel_pool


def initailize_uc(apps, schema_editor):

    TunnelPool = apps.get_model("api", "TunnelPool")

    ips = list(add_tunnel_pool())
    with transaction.atomic():
        for ip in ips:
            TunnelPool.objects.create(ip=ip)

    Defaults = apps.get_model("api", "Defaults")
    Defaults.objects.create()


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [migrations.RunPython(initailize_uc)]
