# Generated by Django 3.1 on 2020-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200820_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaults",
            name="ip_sla_process",
            field=models.CharField(default="214", max_length=3),
        ),
        migrations.AddField(
            model_name="hosts",
            name="hsrp_interface",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="hosts",
            name="primary_router",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="hosts",
            name="virtual_ip",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
