# Generated by Django 3.1.5 on 2021-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200820_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='headend_vendor',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='defaults',
            name='multivendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaults',
            name='vendor_list',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
