# Generated by Django 3.1.5 on 2021-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210823_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
