# Generated by Django 3.1 on 2020-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200826_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hosts",
            name="primary_router",
            field=models.BooleanField(default=False),
        ),
    ]
