# Generated by Django 3.1 on 2020-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200826_1222"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosts",
            name="hsrp",
            field=models.BooleanField(default=False),
        ),
    ]
