# Generated by Django 3.1 on 2020-09-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_hosts_hsrp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hosts",
            old_name="hsrp",
            new_name="fhrp",
        ),
        migrations.RenameField(
            model_name="hosts",
            old_name="hsrp_interface",
            new_name="fhrp_interface",
        ),
    ]
