# Generated by Django 3.1 on 2020-09-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20200910_0941"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lan_routes", models.CharField(blank=True, max_length=20)),
                ("next_hop_lan", models.CharField(blank=True, max_length=20)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="api.hosts",
                    ),
                ),
            ],
        ),
    ]
