# Generated by Django 3.1 on 2020-09-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_routes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routes",
            name="next_hop_lan",
        ),
        migrations.AddField(
            model_name="routes",
            name="custom_route",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
