# Generated by Django 3.1 on 2020-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20200914_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosts",
            name="advertised_interfaces",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="hosts",
            name="advertised_static_routes",
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
