# Generated by Django 3.1.2 on 2020-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200916_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosts",
            name="fqdn",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
