# Generated by Django 3.1.2 on 2020-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_hosts_fqdn"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaults",
            name="hubs_fqds",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="defaults",
            name="nhs_nbma",
            field=models.CharField(default="none", max_length=200),
        ),
        migrations.AlterField(
            model_name="defaults",
            name="nhs_server",
            field=models.CharField(default="none", max_length=200),
        ),
    ]
