# Generated by Django 3.1.2 on 2020-11-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20201027_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaults",
            name="dns",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
