# Generated by Django 3.1.2 on 2020-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20201105_0847"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosts",
            name="ram_size",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
