# Generated by Django 3.1.2 on 2020-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_hosts_ram_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosts",
            name="acl",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="crypto",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="nat",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="routing",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="tcl_scp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="tunnel_int",
            field=models.IntegerField(null=True),
        ),
    ]
