# Generated by Django 3.1.2 on 2020-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20201217_1808"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosts",
            name="snmp_int_index",
            field=models.IntegerField(null=True),
        ),
    ]
