# Generated by Django 3.1.2 on 2021-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_hosts_snmp_int_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaults",
            name="is_copp_configured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="defaults",
            name="is_device_hardening_configured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hosts",
            name="copp_bw",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="logging_configured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hosts",
            name="logging_facility",
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="logging_host",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="logging_level",
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="route_map_prefix_list",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hosts",
            name="vrfs",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="defaults",
            name="hubs_fqds",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
