# Generated by Django 3.1.5 on 2021-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20210120_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="routes",
            name="protocol",
            field=models.TextField(max_length=15, null=True),
        ),
    ]
