# Generated by Django 3.1.5 on 2021-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_routes_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="routes",
            name="advertised",
            field=models.BooleanField(default=False),
        ),
    ]
