# Generated by Django 3.1.5 on 2021-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_routes_advertised"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routes",
            name="protocol",
            field=models.TextField(max_length=10, null=True),
        ),
    ]
